pages:
  image: alpine:latest
  stage: deploy
  script:
    - wget https://github.com/vector-im/element-web/releases/download/v1.7.26/element-v1.7.26.tar.gz
    - tar zvfx element-v1.7.26.tar.gz
    - mv element-v1.7.26 public
    - cp config.json public
  artifacts:
    paths:
      - public
  only:
    - master
