pages:
  image: alpine:latest
  stage: deploy
  variables:
    VERSION: v1.10.6
  script:
    - wget https://github.com/vector-im/element-web/releases/download/${VERSION}/element-${VERSION}.tar.gz
    - tar zvfx element-${VERSION}.tar.gz
    - mv element-${VERSION} public
    - mv config.json public
    - mv background.jpeg public
    - mv default.svg public
  artifacts:
    paths:
      - public
  only:
    - master
