pages:
  image: alpine:latest
  stage: deploy
  script:
    - VERSION=$(curl -s https://api.github.com/repos/element-hq/element-web/releases/latest | grep tag_name | cut -d '"' -f4)
    - wget https://github.com/element-hq/element-web/releases/download/${VERSION}/element-${VERSION}.tar.gz
    - tar zfx element-${VERSION}.tar.gz
    - mv element-${VERSION} public
    - mv config.json public
    - mv background.jpeg public
    - mv default.svg public
  artifacts:
    paths:
      - public
  only:
    - master