pages:
  image: alpine:latest
  stage: deploy
  script:
    - wget https://github.com/vector-im/element-web/releases/download/v1.7.29/element-v1.7.29.tar.gz
    - tar zvfx element-v1.7.29.tar.gz
    - mv element-v1.7.29 public
    - mv config.json public
    - mv background.jpeg public
    - mv default.svg public
  artifacts:
    paths:
      - public
  only:
    - master
